name: "GitHub Action to purge Cloudflare cache"
description: "Purge the cache of an entire Zone or specific files from the Zone"
branding:
  icon: "upload-cloud"
  color: "orange"
runs:
  using: "docker"
  image: "Dockerfile"
